In [2]:
import numpy as np
char_arr = np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
ch_arr2 = np.array(["Supervised","unSupervised","sEMi-supervised","reinforcement"])
low_arr= np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [6]:
cleaned_arr = np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [9]:
array1=np.array([1,2,3,4])
array1.dtype

dtype('int32')

In [11]:
low_arr.dtype

dtype('<U15')

In [12]:
char_arr.dtype

dtype('<U1')

In [15]:
arr1= np.array([1,2,3,4,5],dtype='F')
arr1

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j], dtype=complex64)

In [17]:
arr1= np.array([1,2,3,4,5],dtype='S')
arr1

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [21]:
arr1= np.array([1,2,3,4,5],dtype='f')
arr1

array([1., 2., 3., 4., 5.], dtype=float32)

In [23]:
arr1conv= arr1.astype("i")
arr1conv

array([1, 2, 3, 4, 5], dtype=int32)

In [25]:
arr1againconv= arr1conv.astype("f")
arr1againconv

array([1., 2., 3., 4., 5.], dtype=float32)

In [30]:
char_conv = arr1.astype('U1')
char_conv

array(['1', '2', '3', '4', '5'], dtype='<U1')

Python numpy.ones() function returns a new array of given shape and data type, where element's value is set to 1

In [33]:
ars1= np.ones((3,3), dtype='int')
ars1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
ars1.dtype

dtype('int32')

In [36]:
ars0 = np.zeros((3,3),dtype="int64")
ars0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [42]:
ars3= np.random.random(3)
ars3

array([0.13303818, 0.0165036 , 0.31378015])

In [47]:
dimones = np.ones((4,3,2))
dimones
dimones.ndim

3

In [49]:
ar1=np.array([1,2,3])
ar2=np.array([2,4,6])


In [51]:
power=np.power(ar1,ar2)


In [52]:
array2d = np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])
result=array2d+array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

np.arrange(start,stop,step,dtype=None)

In [53]:
range_arr= np.arange(0,10,3)
range_arr


array([0, 3, 6, 9])

In [54]:
np.random.randint(0,23)

5

In [55]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[2, 1, 2],
       [1, 4, 2]])